_target_: src.models.audioMAE_fine_tune_module.AudioMAEFineTuneModule
sample_rate: 16000
split: 4
zero_shot: False
num_class: 7
optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 1e-4
  betas : [0.9, 0.99]
  