# @package _global_

defaults:
  - _self_
  - data: sc09.yaml # choose datamodule with `test_dataloader()` for evaluation
  - model: diffwave.yaml
  - logger: tensorboard.yaml
  - trainer: gpu.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml
  - experiment: example3_test.yaml

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ???